### ISSUE TITLE
Problems with STI

### ISSUE THREAD

**Issue by kule** [smtlaissezfaire/slugify#1]
Great plugin btw, found it really useful - just thought I'd put a note on here in case someone else has a similar issue as me.

If you use STI, you'll need to put the slugify statement in each of the sub-classes for it to work (at least when using the :when option).

The slugify attributes don't get inherited by the sub-classes so the slugify generator silently fails because the slugify_proc/slugify_when always returns nil.

Cheers
Luke

**Comment by smtlaissezfaire** [comment]
Do you think cattr_reader shoudl be used here instead of attr_reader?

**Comment by kule** [comment]
Maybe a class_inheritable_accessor instead?

See here - http://drnicwilliams.com/2006/08/27/so-cattr_accessor-doesnt-work-like-it-should/

I'll give it a go tomorrow.  I assumed it might be an issue with dynamically extending the class (to include the ClassMethods) as those attributes should be available in the subclass shouldn't they?

**Comment by kule** [comment]
Think I've sussed it - with a little help from this page about acts_as_statemachine:

http://www.ibm.com/developerworks/web/library/j-cb03137/index.html

Give this a go:

http://gist.github.com/207579

Cheers
Luke

**Comment by kule** [comment]
Oh just to clarify - I removed the attr_readers as they were no longer required.

Ta
Luke

**Comment by smtlaissezfaire** [comment]
Cool.  Thanks for the patch.

I actually ran into some weird behavior with class_inheritable_accessor with anonymous classes.  But I've applied the patch anyway, and released 0.1.2.  Thanks!
