### ISSUE TITLE
uninitialized constant Iconv

### ISSUE THREAD

**Issue by kule** [smtlaissezfaire/slugify#3]
```
uninitialized constant Iconv
vendor/plugins/slugify/lib/slugify/slug_generator.rb:9:in `generate_slug'
```

I was getting this error after upgrading my app to Rails 3.  You need to add this to your bundler Gemfile:

```
gem 'iconv'
```

@smtlaissezfaire are you still taking requests for this?  Just wondering about turning this into a gem?

**Comment by smtlaissezfaire** [comment]
Hey kule,

If you'd like to add a gemfile to the project and a gemspec, I'd gladly take a pull request.
